// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttoyahqpblcedkfmydbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0b3lhaHFwYmxjZWRrZm15ZGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTkwNzQsImV4cCI6MjA3MzYzNTA3NH0.2_FkGMbbxzpgaVoSeX5nE7RZvilW6s6MyDbsCHyn7dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});